### PR TITLE
Remove uiToo=false and debounce

### PR DESCRIPTION
**Pull request by jacklehamster**
- uiToo=false : Default params don't work in javascript. Also flagged as error in IntelliJ

### CODE REVIEW

**Comment by leobenkel** [comment]
Thats debounce https://lodash.com/docs/4.17.4#debounce

**Comment by leobenkel** [comment]
Without debounce, you have way more CPU usage because it is being executed every time move is trigger. with debounce, it filters it.

**Comment by jacklehamster** [comment]
Ok, then we need a way to fix this for Firefox, debounce is causing problems

**Comment by leobenkel** [comment]
I fixed the issue on firefox. https://github.com/The-Brains/ChaosGame/pull/14

**Comment by leobenkel** [comment]
Let me know when I can review this pull request after you fix the merge conflicts.

**Review by jacklehamster — COMMENTED** [review]
Just removing uiToo=false

**Pull request merged**
